spring.application.name=fitforge-ai

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/fitforge-ai
spring.datasource.username=postgres
spring.datasource.password=1601

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
