spring.application.name=fitforge-ai

# Database Connection
spring.datasource.url=jdbc:postgresql://postgres:5432/fitforge-ai
spring.datasource.username=rajesh
spring.datasource.password=1601

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=FitForgeSecretKeyForJwtAuthentication12345678901234567890
jwt.expiration=3600000
